linters-settings:
  govet:
    enable:
      - nilness
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - goconst
    - gocritic
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - noctx
    - predeclared
    - stylecheck
    - tparallel
    - unconvert
    - unparam
    - whitespace
run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 1
  tests: true
